name: Train data update

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run scraper script
        run: python scraper.py

      - name: DEBUG - List files
        run: |
          echo "Jelenlegi mappa tartalma:"
          ls -la
          echo "-------------------------"
          if [ -f data.csv ]; then
            echo "A data.csv LÉTEZIK. Mérete:"
            du -h data.csv
          else
            echo "HIBA: A data.csv NEM JÖTT LÉTRE!"
          fi

      - name: Commit and Push
        run: |
          # Csak akkor próbálkozunk, ha létezik a fájl
          if [ -f data.csv ]; then
            git config --global user.name "MAV Bot"
            git config --global user.email "bot@noreply.github.com"
            
            git add data.csv
            
            # Commit (ha nincs változás, nem hal meg a folyamat)
            git commit -m "Auto Update: $(date)" || echo "Nincs új változás a fájlban."
            
            git push
          else
            echo "Nincs data.csv, a commit lépés kimarad."
          fi
